repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.264"
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

  # python code formatting - will amend files
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        additional_dependencies:
          - platformdirs

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args:
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-implicit-optional
          - --ignore-missing-imports
          - --follow-imports=silent
        exclude: ^tests
