version: "3"
services:
    postgres:
        image: postgres:9.6.8
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/data

    elasticsearch:
        image: elasticsearch:7.8.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
